languageCode = "fr-CH"
baseurl = "https://educasuisse.ch/"
title = "Accueil"

[[menu.main]]
    name = "Accueil"
    weight = 0
    url = "/"
[[menu.main]]
    name = "À propos d'Educa-international"
    weight = 10
    identifier = "about"
    url = "/a-propos/"
[[menu.main]]
    name = "Contact"
    weight = 20
    identifier = "contact"
    url = "/contact/"

[blackfriday]
extensions = ["hardLineBreak"]
